### ISSUE TITLE
Import: Specified Entry Must Not Be a Container

### ISSUE THREAD

**Issue by maciekjaros** [Piker-Alpha/freqVectorsEdit.sh#3]
Got this after selecting desired plist. It's alert from PlistBuddy. What's wrong?

**Comment by maciekjaros** [comment]
Just deleted PlistBuddy and let your script download it again. Alert is gone. Maybe you should mention about it in readme?

**Comment by gfoury** [comment]
I bet the script didn’t do anything for you.

If you’re on a board-id like Mac-937CB26E2E02BB01, there are two frequency vectors in an &lt;array&gt;, and this script does not handle that. (It’s listed as a known issue.)

**Comment by maciekjaros** [comment]
Exactly. But this downloaded plistBuddy not communicated error. I have used so far a file with vectors of MBA 6.2. It let me use 800-2700 MHz for my i5-5200U I'm waiting for update :)

**Comment by gfoury** [comment]
Oh, thank you, I’ll try MBA6,2.

**Comment by gfoury** [comment]
I’ll will try to change the shell script to modify &lt;array&gt;s of vectors. sh isn’t my favorite language, though...

**Comment by Piker-Alpha** [comment]
FrequencyVectors are becoming more and more complex. For example. Some Apple models, like the MacBook8,[1/2] are available with different processors, and for each model there is a 'FrequencyVectors' item that, in this case, even limits the maximum turbo frequency to either 2400 MHz, 2600 MHz or 2900 MHz for the fastest model. And for this to work, Apple first reads the 'Frequencies' property and then they know what item to use (0, 1, or 2) but the maximum turbo frequency may not match with the processor in your hack and thus we need to add a new argument (-turbo) so that we can try to match it, or let the end-user pick one. What we can do, or should do perhaps, is to remove the 'Frequencies' property and inject the copied FrequencyVectors data (a single item).

Then there is a 'CPUFloor' property, which may not be there, but this can be used to set the minimum frequency, and that may not be what people want. Next to that, for Broadwell, there is a value in the FrequencyVectors data that does the same. Again. Which may not be what people want, or expect.

See also: https://github.com/Piker-Alpha/ssdtPRGen.sh/issues/198

@maciekjaros,

You have a Broadwell processor and should use matching data. Not that of a Haswell based  model.

**Comment by gfoury** [comment]
Let me summarize what I think you've said. (I would probably write the plist hacking in Python, which is much easier for me than PlistBuddy. You don't need to use anything I write, of course.)

To handle board-ids with multiple FrequencyVectors:
- Set `CPUFloor`
- Find/patch a `Frequency`
- Produce the corresponding `FrequencyVector` as a binary file in /tmp
- Patch as normal
- Move the patched `FrequencyVector` back to the right place in the plist

In the short term, I need to do something for MacBookAir7,2. To do exactly what you asked @anerik70 to do to MB8,1 in Piker-Alpha/ssdtPRGen.sh#198:
- Command line arguments: `-turbo`, `-low-frequency`
- Look up the board-id in `/S/L/E/IOPlatformPlugin*/C/P/X86PlatformPlugin/Contents/Resources`
- Set `CPUFloor` to the processor's _low-frequency_
- Find the closest `Frequency` at or below _turbo_ This is _oldturbo_.
  - If we didn't find an exact match to _turbo_, change the matched `Frequency` to _turbo_
- Working with the `FrequencyVector` corresponding to the `Frequency` we picked:
  - Patch offset 0x4 with the CPU's low frequency
  - If we changed the _turbo_, look for _oldturbo_ "xx000000 01000000" and set it to the new _turbo_. This should happen 0 (MBA7,2) or 1 (MB8,1) times.

This is a total kludge because I don't understand FrequencyVectors. Maybe I will restrict it to the MacBookAir7,2 and MacBook8,1 board-ids.

**Comment by Piker-Alpha** [comment]
This issue is fixed in v2.3
